// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obuppulglkqksmpxnveo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9idXBwdWxnbGtxa3NtcHhudmVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTUzMzcsImV4cCI6MjA2NDAzMTMzN30.W0fuB-o2_jJ1M2gB8OwJjhxuJk05ZFmwhDuLisQJOZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});